const input=document.getElementById('inputText'),output=document.getElementById('outputText'),inCount=document.getElementById('inputCount'),outCount=document.getElementById('outputCount'),copy=document.getElementById('copyBtn');let level='light',mode='humanize',history=[];
const words=s=>s.trim()?s.trim().split(/\s+/).length:0;const update=()=>inCount.textContent=words(input.value)+' words';input.addEventListener('input',update);
document.querySelectorAll('.level-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.level-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');level=b.dataset.level});
document.querySelectorAll('.feature-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.feature-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;document.getElementById('humanizeBtn').innerHTML='<span class="spark">✦</span> '+({humanize:'Humanize text',paraphrase:'Paraphrase text',shorten:'Shorten text',expand:'Expand text',grammar:'Improve grammar'}[mode])+' <span>↗</span>'});
document.getElementById('creativity').oninput=e=>{document.getElementById('creativityValue').textContent=e.target.value<35?'Conservative':e.target.value>65?'Creative':'Balanced'};
document.getElementById('clearBtn').onclick=()=>{input.value='';update();output.textContent='Your transformed writing will appear here.';output.className='output-placeholder';outCount.textContent='0 words';copy.disabled=true};
document.getElementById('sampleBtn').onclick=()=>{input.value='In conclusion, it is important to note that artificial intelligence has become an increasingly significant part of our everyday lives. Furthermore, it is essential that we consider the various ways in which this technology can impact society in the future.';update();input.focus()};
document.getElementById('pasteBtn').onclick=async()=>{try{input.value=await navigator.clipboard.readText();update()}catch{input.focus()}};
function transform(text){let s=text.trim();const reps=[[/\bin conclusion,?\b/gi,'Ultimately'],[/\bit is important to note that\b/gi,''],[/\bit is essential that we consider\b/gi,'we should consider'],[/\ba significant part of\b/gi,'a meaningful part of'],[/\bincreasingly significant\b/gi,'important'],[/\bfurthermore,?\b/gi,'Also'],[/\butilize\b/gi,'use'],[/\bvarious ways in which\b/gi,'ways'],[/\bin order to\b/gi,'to'],[/\bdue to the fact that\b/gi,'because'],[/\bat this point in time\b/gi,'now'],[/\bhas the ability to\b/gi,'can'],[/\bfor the purpose of\b/gi,'to']];reps.forEach(([r,v])=>s=s.replace(r,v));if(mode==='shorten')s=s.replace(/\b(very|really|quite|basically|in fact|actually)\b/gi,'').replace(/,?\s*(which|that)\s+[^,.!?]+/gi,'');if(mode==='expand')s=s.replace(/\.\s+/g,'. This is an important consideration. ');if(mode==='grammar')s=s.replace(/\bi\b/g,'I').replace(/\s{2,}/g,' ');if(level!=='light')s=s.replace(/\bit should be noted that\b/gi,'Notably').replace(/\bthere are a number of\b/gi,'several');s=s.replace(/,\s*,/g,',').replace(/\s{2,}/g,' ').replace(/\s+([,.!?])/g,'$1');return s.replace(/(^|[.!?]\s+)([a-z])/g,(m,a,b)=>a+b.toUpperCase())}
document.getElementById('humanizeBtn').onclick=()=>{if(!input.value.trim()){input.focus();return}const btn=document.getElementById('humanizeBtn');btn.disabled=true;btn.innerHTML='<span class="spark">✦</span> Working…';setTimeout(()=>{const result=transform(input.value);output.textContent=result;output.className='output-placeholder ready';outCount.textContent=words(result)+' words';copy.disabled=false;history.unshift({mode,text:result,time:new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})});history=history.slice(0,5);btn.disabled=false;btn.innerHTML='<span class="spark">✦</span> '+({humanize:'Humanize text',paraphrase:'Paraphrase text',shorten:'Shorten text',expand:'Expand text',grammar:'Improve grammar'}[mode])+' <span>↗</span>'},500)};
copy.onclick=async()=>{await navigator.clipboard.writeText(output.textContent);copy.textContent='Copied ✓';setTimeout(()=>copy.textContent='Copy text',1500)};
document.getElementById('historyBtn').onclick=()=>{document.getElementById('historyPanel').classList.toggle('open');document.getElementById('historyList').innerHTML=history.length?history.map((h,i)=>`<button class="history-item" data-i="${i}"><b>${h.mode}</b><span>${h.text.slice(0,70)}…</span><small>${h.time}</small></button>`).join(''):'<p class="empty-history">Your recent drafts will show up here.</p>';document.querySelectorAll('.history-item').forEach(x=>x.onclick=()=>{output.textContent=history[x.dataset.i].text;output.className='output-placeholder ready';outCount.textContent=words(output.textContent)+' words'})};document.getElementById('closeHistory').onclick=()=>document.getElementById('historyPanel').classList.remove('open');document.getElementById('themeBtn').onclick=()=>document.body.classList.toggle('dark');